### ISSUE TITLE
cannot build the package

### ISSUE THREAD

**Issue by Etol1LC** [Leofltt/Kairos#1]
Hello Leo, I am trying to install on MacOs Catalina via cabal and  I get the following error:

etol@Claudios-Air Kairos-master % cabal update
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2021-06-12T08:40:57Z
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2021-05-06T03:27:42Z'
etol@Claudios-Air Kairos-master % cabal install
Wrote tarball sdist to
/Users/etol/Desktop/Kairos-master/dist-newstyle/sdist/Kairos-0.3.2.tar.gz
Resolving dependencies...
cabal: Cannot build the executables in the package Kairos because it does not
contain any executables. Check the .cabal file for the package and make sure
that it properly declares the components that you expect.

**Comment by Leofltt** [comment]
Ciao Claudio prova questo workaround:

`cabal install --lib`

se non ti da errori puoi verificare l'installazione facendo `ghci` e da dentro ghci `:m Kairos.Lib` e dovrebbe caricarti la libreria

se comunque non funziona prova:

`vi /Users/*iltuousername*/.cabal/config`

cambia queste due lines dopo averle uncommentate se sono commentate:

`library-profiling: False`
e
`documentation: False`

dopodichè esci e salva (esc e poi `:wq` in questo caso con vim). 

Riprova a fare `cabal install --lib` e dovrebbe crearti una build in un sandbox a cui puoi accedere usando `cabal repl` 

In questi giorni aggiorno la documentazione per spiegare meglio come far funzionare tutto, ma se hai tempo di provare a far queste cose fino a cabal install e mi puoi dire se funziona sarebbe super d'aiuto

**Comment by Etol1LC** [comment]
Ciao Leo! Ho provato la procedura. Fino a cabal build. Funziona. Nessun
error msg durante il build. Attendo istruzioni su come procedere.

Ciao e Grazie
Claudio

Il giorno lun 5 lug 2021 alle ore 22:37 Leo Foletto <
***@***.***> ha scritto:
